apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector: 
    app: nexus-server
  type: NodePort
  ports:
    - port: 8081
      name: nexusport
      targetPort: 8081
      nodePort: 32000
    - port: 5003
      name: dockerport
      targetPort: 5003
      nodePort: 32001
